"""
Django settings for controle_gastos project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

####base dir guarda caminho de onde está sistema operacional
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

###a string do secret key criptografa senhas etc  
SECRET_KEY = 'django-insecure-ab4$$n6f+t)n+h*y$52*^2c0m!@2#%_f^w4-(ul9t2djf()_tv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True ###true em desenvolvimento para mostrar detalhes. em produção desativa para o usuário nao ver as paradas do sistema 

ALLOWED_HOSTS = [] ###o parametro é os domínios onde a aplicação funciona


# Application definition

INSTALLED_APPS = [ ###aplicações instaladas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contas', ###aplicação contas registrada 
]

MIDDLEWARE = [  ###coisas legais que o django faz 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'controle_gastos.urls' ###configuração de urls

TEMPLATES = [ ##config relacionadas a template
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'controle_gastos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = { ###bancos de dados configurados por padrão, funciona com sqlite3, sendo chamado de framework com pilhas inclusas 
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', ### por padrão o bd criado é o sqlite 3. pra criar poutro bd tem que ver na documentaçãoo, que está 4 linhas acima https://docs.djangoproject.com/en/4.1/ref/settings/#databases
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', ### verifica se a senha é muito parecida com o nome de usuário
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', ###tamanho mínimo
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', ###senhas muito comuns
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', ###senhas somente numéricas
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/' ### endereço de onde vai colocar os aqrquivos estátivos css html js etc

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
